name: Cross-Platform Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            artifact_name: dapptoon-linux-amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            artifact_name: dapptoon-windows-amd64.exe
          - os: macos-latest
            goos: darwin
            goarch: amd64
            artifact_name: dapptoon-darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            artifact_name: dapptoon-darwin-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go mod tidy
        go build -v -o ${{ matrix.artifact_name }} ./main.go

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/dapptoon-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}